config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :companeros

   root to: 'companeros#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/companero.rb
class Companero < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companeros_controller.rb
class CompanerosController < ApplicationController
  before_action :set_companero, only: [:show, :edit, :update, :destroy]

  # GET /companeros
  # GET /companeros.json
  def index
    @companeros = Companero.all
  end

  # GET /companeros/1
  # GET /companeros/1.json
  def show
  end

  # GET /companeros/new
  def new
    @companero = Companero.new
  end

  # GET /companeros/1/edit
  def edit
  end

  # POST /companeros
  # POST /companeros.json
  def create
    @companero = Companero.new(companero_params)

    respond_to do |format|
      if @companero.save
        format.html { redirect_to @companero, notice: 'Mascota creada con exito.' }
        format.json { render :show, status: :created, location: @companero }
      else
        format.html { render :new }
        format.json { render json: @companero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companeros/1
  # PATCH/PUT /companeros/1.json
  def update
    respond_to do |format|
      if @companero.update(companero_params)
        format.html { redirect_to @companero, notice: 'Mascota editada con exito.' }
        format.json { render :show, status: :ok, location: @companero }
      else
        format.html { render :edit }
        format.json { render json: @companero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companeros/1
  # DELETE /companeros/1.json
  def destroy
    @companero.destroy
    respond_to do |format|
      format.html { redirect_to companeros_url, notice: 'Mascota eleiminada con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_companero
      @companero = Companero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def companero_params
      params.require(:companero).permit(:nombre, :edad, :raza, :dueno, :descripcion, :color, :peso, :tamano, :foto)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Cita agendada con exito.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Cita modificada con exito.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Cita eliminada con exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :nombre, :start, :hora)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companeros_helper.rb
module CompanerosHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/companeros/_form.html.erb
<center>
<%= form_for(companero) do |f| %>
  <% if companero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(companero.errors.count, "error") %> prohibited this companero from being saved:</h2>

      <ul>
      <% companero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :Edad %>
    <%= f.number_field :edad %>
  </div>

  <div class="field">
    <%= f.label :Raza %>
    <%= f.select :raza, ['Husky','Labrador','Pug','Beagle','Pastor aleman','Rottweiler','Caniche','Shih Tzu','Bulldog']  %>
  </div>

  <div class="field">
    <%= f.label :Dueño %>
    <%= f.text_field :dueno %>
  </div>

  <div class="field">
    <%= f.label :Descripción %>
    <%= f.text_field :descripcion %>
  </div>

  <div class="field">
    <%= f.label :Color %>
    <%= f.select :color, ['Pimienta','Gris','Negro','Blanco','Sesamo','Fuego']%>
  </div>

  <div class="field">
    <%= f.label :Peso %>
    <%= f.text_field :peso %>
  </div>

  <div class="field">
    <%= f.label :Tamaño %>
    <%= f.text_field :tamano %>
  </div>

  <div class="field">
    <%= f.label :Foto %>
    <%= f.file_field :foto %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</center>

app/views/companeros/edit.html.erb
<center>
<h1>Editando mascota</h1>

<%= render 'form', companero: @companero %>

<%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, @companero %> |
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, companeros_path %>

</center>

app/views/companeros/index.html.erb
<center>
<p id="notice"><%= notice %></p>

<h1>Mascotas</h1>

<table  WIDTH="100%">
  <thead>
    <tr>
    <th>Foto</th>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Raza</th>
      <th>Dueño</th>
      <th>Descripción</th>
      <th>Color</th>
      <th>Peso</th>
      <th>Tamaño</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companeros.each do |companero| %>
        <td></td>
        <td><%= companero.nombre %></td>
        <td><%= companero.edad %></td>
        <td><%= companero.raza %></td>
        <td><%= companero.dueno %></td>
        <td><%= companero.descripcion %></td>
        <td><%= companero.color %></td>
        <td><%= companero.peso %></td>
        <td><%= companero.tamano %></td>
        <td><%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, companero %></td>
        <td><%= link_to '<button type="button" class="button success small">Editar</button>'.html_safe, edit_companero_path(companero) %></td>
        <td><%= link_to '<button type="button" class="button alert small">Eliminar!</button>'.html_safe, companero, method: :delete, data: { confirm: '¿Estas seguro?' } %>
    
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<button type="button" class="button success basic">Citas</button>'.html_safe, events_path %>
<%= link_to '<button type="button" class="button expanded warning">Nueva mascota</button>'.html_safe, new_companero_path %>
</center>

app/views/companeros/new.html.erb
<center><h1>Nueva mascota</h1>

<%= render 'form', companero: @companero %>


<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, companeros_path %>
</center>

app/views/companeros/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="large-8 columns">

  </div>
<div class="large-4 columns">
<p>
  <strong>Nombre:</strong>
  <%= @companero.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @companero.edad %>
</p>

<p>
  <strong>Raza:</strong>
  <%= @companero.raza %>
</p>

<p>
  <strong>Dueño:</strong>
  <%= @companero.dueno %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @companero.descripcion %>
</p>

<p>
  <strong>Color:</strong>
  <%= @companero.color %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @companero.peso %>
</p>

<p>
  <strong>Tamaño:</strong>
  <%= @companero.tamano %>
</p>
</div>
</div>
<center>
<%= link_to '<button type="button" class="button success basic">Editar</button>'.html_safe, edit_companero_path(@companero) %> |
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, companeros_path %>
</center>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre_del_dueño %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :Nombre_de_la_mascota %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :Fecha %>
    <%= f.date_select :start %>
  </div>

 <div class="field">
    <%= f.label :Hora %>
    <%= f.time_select :hora %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<center>
<h1>Editanto cita</h1>

<%= render 'form', event: @event %>

<%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, @event %> |
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, events_path %>

</center>

app/views/events/index.html.erb
<style>
        #calendar {
            width: 80%;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
         
        .centered {
            text-align: center;
        }
    </style>
    
<center>
<p id="notice"><%= notice %></p>

<h1>Citas</h1>

<table WIDTH="100%">
  <thead>
    <tr>
      <th>Dueño de la mascota</th>
      <th>Nombre de la mascota</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.nombre %></td>
        <td><%= event.start %></td>
        <td><%= event.hora %></td>
        <td><%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, event %></td>
        <td><%= link_to '<button type="button" class="button success small">Editar</button>'.html_safe, edit_event_path(event) %></td>
        <td><%= link_to '<button type="button" class="button alert small">Eliminar!</button>'.html_safe, event, method: :delete, data: { confirm: '¿Estas seguro?' } %>
    
      
      
      
        </tr>
    <% end %>
  </tbody>
</table>

<div id="calendar" class="calendar"> 
<script>
    $('#calendar').fullCalendar({
    })
</script>
</div>
<br>

<%= link_to '<button type="button" class="button success basic">Mascotas</button>'.html_safe, companeros_path %>
<%= link_to '<button type="button" class="button expanded warning">Agendar cita</button>'.html_safe, new_event_path %>

</center>

app/views/events/new.html.erb
<center>
<h1>Agendar cita</h1>

<%= render 'form', event: @event %>

<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, events_path %>

</center>

app/views/events/show.html.erb
<center>
<p id="notice"><%= notice %></p>

<p>
  <strong>Dueño:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Nombre de la mascota:</strong>
  <%= @event.nombre %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @event.hora %>
</p>

<%= link_to '<button type="button" class="button success basic">Editar</button>'.html_safe, edit_event_path(@event) %> |
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, events_path %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  
  
  </head>

  <body>
  <div id="calendar"> 
<script>
    $('#calendar').fullCalendar({
      events: <%= @events.to_json.html_safe %>
    })
</script>
</div>
  

    <%= yield %>
    
  </body>
</html>